name: Create Repository

on:
  workflow_dispatch:
    inputs:
      repository_name:
        description: "Nombre del repositorio"
        required: true
        type: string

      port_run_id:
        description: "ID de la ejecución de Port"
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Mostrar información
        run: |
          echo "Repositorio solicitado: ${{ inputs.repository_name }}"
          echo "Port Run ID: ${{ inputs.port_run_id }}"

      - name: Actualizar estado en Port
        uses: port-labs/port-github-action@v1
        with:
          clientId: ${{ secrets.PORT_CLIENT_ID }}
          clientSecret: ${{ secrets.PORT_CLIENT_SECRET }}
          baseUrl: https://api.port.io
          operation: PATCH_RUN
          runId: ${{ inputs.port_run_id }}
          status: SUCCESS
          logMessage: "Workflow ejecutado correctamente en GitHub"
